config/routes.rb
Tumimo::Application.routes.draw do
  match 'sign_in' => "sign_in#index"

  get "analysis/index"
  get 'analysis/facebook'

  resources :users

  get "home/index"
  get "sessions/create"
  get "sessions/destroy"

  resources :authentications
  resources :channels
  
  match '/auth/:provider/callback' => 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'analysis#index'
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController
  before_filter :require_signed_in

  def index
  end

  def facebook
  	@me = current_user.send_job('me').try(:[],'data').try(:[],'raw')
  	@friend_ids = current_user.send_job('friend_ids').try(:[],'data').try(:[],'raw')
  	@feed = current_user.send_job('feed').try(:[],'data').try(:[],'raw')
  	#@me = current_user.mfb.me['data']['raw']
  	# @friend_ids = current_user.mfb.friend_ids['data']['raw']
  end
end

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/views/analysis/facebook.html.erb
<% processing = '-' %>
<section id="personal_information">
	<div class="page-header"><h1>About Yourself</h1></div>
	<table class="table table-hover table-condensed table-striped table-bordered">
		<tbody>
			<tr>
				<td>Name</td>
				<td><%= @me.try(:[],'name') || processing %></td>
			</tr>
			<tr>
				<td>Birthday</td>
				<td><%= @me.try(:[],'birthday') || processing  %></td>
			</tr>			
			<tr>
				<td>Hometown</td>
				<td><%= @me.try(:[],'hometown').try(:[],'name') || processing  %></td>
			</tr>
			<tr>
				<td>Work</td>
				<% position =  @me.try(:[],'work').try(:[],0).try(:[],'position').try(:[],'name') %>
				<% workplace =  @me.try(:[],'work').try(:[],0).try(:[],'employer').try(:[],'name') %>
				<% work = [position,workplace].compact.join(" at ") %>
				<td><%= work.blank? ? '-' : work  %></td>
			</tr>
			<tr>
				<td>Opened Facebook on</td>
				<% date = Time.parse(@feed.last["created_time"]).strftime("%b/%d/%Y") rescue nil %>
				<td><%= date || '-'  %></td>
				<!-- http://stackoverflow.com/questions/7332957/determine-when-user-created-facebook-account -->
				<!-- November 3, 2007 -->
			</tr>			
		</tbody>
	</table>
</section>

<%# p = fb.user_feeds %>
<section id="posts_information">
<!-- http://developers.facebook.com/docs/reference/api/post/ -->
<!-- https://graph.facebook.com/me/feed -->
<!-- 
counting rows:
http://blogs.x2line.com/al/archive/2007/10/07/3287.aspx
SELECT '' 
  FROM user 
 WHERE uid IN (SELECT uid2 
                 FROM friend 
                WHERE uid1 = USERID)
   AND has_added_app = 1


SELECT post_id, type, message,description, permalink 
FROM stream 

WHERE 
source_id= me() and actor_id = me() 
and (message != "")
and created_time < 1285891200 
LIMIT 5000
 -->
	<div class="page-header"><h1>Your Posts</h1></div>
	<table class="table table-hover table-condensed table-striped table-bordered">
		<tbody>
			<tr>
				<td>Total Wall Posts</td>
				<td><%= @feed.try(:count) || processing  %></td>
			</tr>
			<tr>
				<!-- f.map{|t| t.try(:[], 'likes').try(:[],'count')}.compact -->
				<td>10 Top Most Liked Posts</td>
				<td><%= "" || processing  %></td>
			</tr>
			<tr>
				<!-- f.map{|t| [t.try(:[], 'comments').try(:[],'count'), t['id']]}.compact.sort -->
				<td>10 Top Most Commented Posts</td>
				<td><%= "" || processing  %></td>
			</tr>			
		</tbody>
	</table>
</section>

<section id="friends_information">
	<div class="page-header"><h1>Friends</h1></div>
	<table class="table table-hover table-condensed table-striped table-bordered">
		<tbody>
			<tr>
				<td>Friends Count</td>
				<td><%= @friend_ids.try(:count) || processing %></td>
			</tr>
			<tr>
				<td>Groups</td>
				<td><%= "" || processing  %></td>
			</tr>				
		</tbody>
	</table>
	<div>Graph</div>
	<div>History</div>
	<div>Locations (where are your friends now?)</div>
	<div>Single Friends</div>
</section>

app/views/analysis/index.html.erb
<% content_for :sidebar do %>
	<div class="well sidebar-nav">
	  <ul class="nav nav-list">
	    <li class="nav-header"><%= current_user.name %></li>
	    <li class="active"><%= link_to 'Facebook', analysis_facebook_path %></li>
	    <li><%= link_to 'Twitter', '#'  %></li>
	  </ul>
	</div><!--/.well -->
<% end %>

<h1>Analysis#index</h1>
<p>Find me in app/views/analysis/index.html.erb</p>