config/routes.rb
Tumimo::Application.routes.draw do
  match 'sign_in' => "sign_in#index"

  get "analysis/index"
  get 'analysis/facebook'

  resources :users

  get "home/index"
  get "sessions/create"
  get "sessions/destroy"

  resources :authentications
  resources :channels
  
  match '/auth/:provider/callback' => 'sessions#create'
  match 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'analysis#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tumimo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>
    
    <!-- Toolbar -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Tumimo</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to 'Analysis', '#' %></li>
              <li><%= link_to 'Influence', '#' %></li>
              <li class="divider-vertical"></li>
              <li><%= link_to "Users", users_path  %></li>
              <li><%= link_to "Authentications", authentications_path  %></li>
            </ul>
            <ul class="nav pull-right">
            	<% if user_signed_in? %>
            		<li class="dropdown">
            			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
            				<i class="icon-user"></i>
            				<%= current_user.try(:name) || current_user.try(:email) || current_user.try(:authentication_id) %>
            				<b class="carret"></b>
            			</a>
            			<ul class="dropdown-menu">
            				<li><%= link_to raw('<i class="icon-cog"></i> Profile'), edit_user_path(current_user)  %></li>
            				<li class="divider"></li>
            				<li><%= link_to raw('<i class="icon-off"></i> Logout'), signout_path, :method => :delete %></li>
            			</ul>
            		</li>
              <% else %>
                <li><%= link_to "Sign in", '#' %></li>
            	<% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <!-- /toolbar -->

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <% if content_for? :sidebar %>
            <%= yield :sidebar %>
          <% end %>
        </div><!--/span-->
        <div class="span9">
					<% if notice || flash.key?(:notice) %>
						<div class="alert alert-info">
							<button class="close" data-dismiss="alert">x</button>
							<strong><%= notice || flash[:notice] %></strong>
						</div>
					<% end %>
					<% if alert || flash.key?(:alert) %>
						<div class="alert alert-block">
							<button class="close" data-dismiss="alert">x</button>
							<strong><%= alert || flash[:alert] %></strong>
						</div>
					<% end %>					
					<% if flash.key?(:error) %>
						<div class="alert alert-error">
							<button class="close" data-dismiss="alert">x</button>
							<strong><%= flash[:error] %></strong>
						</div>
					<% end %>					
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Tumimo 2012 by <%= link_to 'Adrian Mejia', 'http://adrianmejia.com' %></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>